title: Coding Challenge "Bottle Sets"
email: fertmeneses@gmail.com
logo: assets/CC_bottle_logo.png
description: Open coding challenge for data analysis skills, by Fernando Meneses.
show_downloads: True
theme: jekyll-theme-minimal
